Starting SSH check for instances...
WARNING: 

To increase the performance of the tunnel, consider installing NumPy. For instructions,
please see https://cloud.google.com/iap/docs/using-tcp-forwarding#increasing_the_tcp_upload_bandwidth

WARNING: 

To increase the performance of the tunnel, consider installing NumPy. For instructions,
please see https://cloud.google.com/iap/docs/using-tcp-forwarding#increasing_the_tcp_upload_bandwidth

WARNING: 

To increase the performance of the tunnel, consider installing NumPy. For instructions,
please see https://cloud.google.com/iap/docs/using-tcp-forwarding#increasing_the_tcp_upload_bandwidth

WARNING: 

To increase the performance of the tunnel, consider installing NumPy. For instructions,
please see https://cloud.google.com/iap/docs/using-tcp-forwarding#increasing_the_tcp_upload_bandwidth

WARNING: 

To increase the performance of the tunnel, consider installing NumPy. For instructions,
please see https://cloud.google.com/iap/docs/using-tcp-forwarding#increasing_the_tcp_upload_bandwidth

ERROR: [0] Error during local connection to [stdin]: Error while connecting [4003: 'failed to connect to backend']. (Failed to connect to port 22)
Traceback (most recent call last):
  File "/mnt/c/Users/Erry/AppData/Local/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/command_lib/compute/iap_tunnel.py", line 775, in RunReceiveLocalData
    websocket_conn = self._InitiateConnection(
  File "/mnt/c/Users/Erry/AppData/Local/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/command_lib/compute/iap_tunnel.py", line 744, in _InitiateConnection
    new_websocket.InitiateConnection()
  File "/mnt/c/Users/Erry/AppData/Local/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/iap_tunnel_websocket.py", line 152, in InitiateConnection
    self._WaitForOpenOrRaiseError()
  File "/mnt/c/Users/Erry/AppData/Local/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/iap_tunnel_websocket.py", line 444, in _WaitForOpenOrRaiseError
    raise ConnectionCreationError(error_msg)
googlecloudsdk.api_lib.compute.iap_tunnel_websocket.ConnectionCreationError: Error while connecting [4003: 'failed to connect to backend']. (Failed to connect to port 22)
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535

Recommendation: To check for possible causes of SSH connectivity issues and get
recommendations, rerun the ssh command with the --troubleshoot option.

gcloud compute ssh elk-test --project=datalabs-hs --zone=asia-southeast2-b --troubleshoot

Or, to investigate an IAP tunneling issue:

gcloud compute ssh elk-test --project=datalabs-hs --zone=asia-southeast2-b --troubleshoot --tunnel-through-iap

ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
Error: Could not SSH into elk-test in asia-southeast2-b using IAP
WARNING: 

To increase the performance of the tunnel, consider installing NumPy. For instructions,
please see https://cloud.google.com/iap/docs/using-tcp-forwarding#increasing_the_tcp_upload_bandwidth

WARNING: 

To increase the performance of the tunnel, consider installing NumPy. For instructions,
please see https://cloud.google.com/iap/docs/using-tcp-forwarding#increasing_the_tcp_upload_bandwidth

ERROR: [0] Error during local connection to [stdin]: Error while connecting [4003: 'failed to connect to backend']. (Failed to connect to port 22)
Traceback (most recent call last):
  File "/mnt/c/Users/Erry/AppData/Local/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/command_lib/compute/iap_tunnel.py", line 775, in RunReceiveLocalData
    websocket_conn = self._InitiateConnection(
  File "/mnt/c/Users/Erry/AppData/Local/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/command_lib/compute/iap_tunnel.py", line 744, in _InitiateConnection
    new_websocket.InitiateConnection()
  File "/mnt/c/Users/Erry/AppData/Local/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/iap_tunnel_websocket.py", line 152, in InitiateConnection
    self._WaitForOpenOrRaiseError()
  File "/mnt/c/Users/Erry/AppData/Local/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/iap_tunnel_websocket.py", line 444, in _WaitForOpenOrRaiseError
    raise ConnectionCreationError(error_msg)
googlecloudsdk.api_lib.compute.iap_tunnel_websocket.ConnectionCreationError: Error while connecting [4003: 'failed to connect to backend']. (Failed to connect to port 22)
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535

Recommendation: To check for possible causes of SSH connectivity issues and get
recommendations, rerun the ssh command with the --troubleshoot option.

gcloud compute ssh gitlab-test-1 --project=datalabs-hs --zone=asia-southeast2-b --troubleshoot

Or, to investigate an IAP tunneling issue:

gcloud compute ssh gitlab-test-1 --project=datalabs-hs --zone=asia-southeast2-b --troubleshoot --tunnel-through-iap

ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
Error: Could not SSH into gitlab-test-1 in asia-southeast2-b using IAP
SSH check completed for 7 instances. Failures: 2.
